// Auto-generated index file for checkout/icons
export { AimIcon } from './aim';
export { ClipboardIcon } from './clipboard';
export { DefaultIcon } from './default';
export { DualEmailIcon } from './dual-email';
export { DualImageIcon } from './dual-image';
export { GoogleIcon } from './google';
export { GrowthIcon } from './growth';
export { ImageAdsIcon } from './image-ads';
export { ImageIcon } from './image';
export { LikeIcon } from './like';
export { LinkIcon } from './link';
export { MailIcon } from './mail';
export { OptionsIcon } from './options';
export { PencilIcon } from './pencil';
//export { UserPlusIcon } from './user-plus';
export { VideoAdsIcon } from './video-ads';
export { VideoIcon } from './video';
